"""default

Revision ID: 69c98ffbbae7
Revises: 
Create Date: 2025-03-13 11:27:51.910257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69c98ffbbae7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('referral_id', sa.BIGINT(), nullable=True),
    sa.Column('refer', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('private_key_encrypted', sa.String(length=512), nullable=True),
    sa.Column('transactions', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('amount_tx', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('referral_bonus', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###